[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/img/*"
  to = "/img/:splat"
  status = 200

[[redirects]]
  from = "/video/*"
  to = "/video/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 